<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CzwsEAg' shared service.

return $this->privates['.service_locator.CzwsEAg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'animal' => array('privates', '.errored..service_locator.CzwsEAg.App\\Entity\\Animal', NULL, 'Cannot autowire service ".service_locator.CzwsEAg": it references class "App\\Entity\\Animal" but no such service exists.'),
));
