<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZzC6hsv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZzC6hsv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZzC6hsv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZzC6hsv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZzC6hsv\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'ZzC6hsv',
    'container.build_id' => 'b785958d',
    'container.build_time' => 1545850464,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZzC6hsv');
