<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR10Dzwx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR10Dzwx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR10Dzwx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR10Dzwx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR10Dzwx\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'R10Dzwx',
    'container.build_id' => 'b73cf45c',
    'container.build_time' => 1545832489,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerR10Dzwx');
