<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSlwkNhZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSlwkNhZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSlwkNhZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSlwkNhZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSlwkNhZ\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'SlwkNhZ',
    'container.build_id' => 'eb784def',
    'container.build_time' => 1545997483,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSlwkNhZ');
